name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install frontend dependencies
      working-directory: web/frontend
      run: npm ci
    - name: Run frontend unit tests
      working-directory: web/frontend
      run: npm test
    - name: Run Playwright tests
      if: hashFiles('web/frontend/playwright.config.*') != ''
      working-directory: web/frontend
      run: |
        npx playwright install --with-deps
        npx playwright test
    - name: Run Cypress tests
      if: hashFiles('web/frontend/cypress.config.*') != ''
      working-directory: web/frontend
      run: npx cypress run
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx
    - name: Run Python tests
      run: pytest -v

  ios-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run iOS UI tests
      run: |
        xcodebuild test -project ios/MindfulConnect.xcodeproj \
          -scheme MindfulConnect \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
